# config_gpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-standard-1
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/dtumlops-374307/project_docker
