# name: model-training
# on: [push]
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     container: ghcr.io/iterative/cml:0-dvc2-base1
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#       - uses: actions/checkout@v3
#       - id: 'auth'
#         name: 'Authenticate to Google Cloud'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           workload_identity_provider: 'projects/1037547109290/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#           service_account: 'my-service-account@dtumlops-374307.iam.gserviceaccount.com'
#       - name: Train model
#         # env:
#         #   GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#         run: |
#           # Install requirements
#           pip install -r requirements.txt
          
#           # Pull data & run-cache from S3 and reproduce pipeline
#           dvc pull model_v1_0.pth

          

#           python main.py


name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:

      - uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/1037547109290/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@dtumlops-374307.iam.gserviceaccount.com'


      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
  
      - uses: actions/cache@v3
        with:
          path: ${{ steps.cache-path.outputs.dir }}
          key: ${{ hashFiles('**/requirements.txt') }}

      - name: Install requirements
        run: |
          #  Install requirements
          pip install -r requirements.txt  

      

      

     
