# name: model-training
# on: [push]
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     container: ghcr.io/iterative/cml:0-dvc2-base1
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#       - uses: actions/checkout@v3
#       - id: 'auth'
#         name: 'Authenticate to Google Cloud'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           workload_identity_provider: 'projects/1037547109290/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#           service_account: 'my-service-account@dtumlops-374307.iam.gserviceaccount.com'
#       - name: Train model
#         # env:
#         #   GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#         run: |
#           # Install requirements
#           pip install -r requirements.txt
          
#           # Pull data & run-cache from S3 and reproduce pipeline
#           dvc pull model_v1_0.pth

          

#           python main.py
        

name: Train-in-the-cloud
on: [push]
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/1037547109290/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@dtumlops-374307.iam.gserviceaccount.com'
        run: |
          cml runner launch \
            --cloud=gcp \
            --cloud-region=europe-west4-b \
            --cloud-gpu=nvidia-tesla-t4
            --labels=cml-gpu

  train-model:
    needs: deploy-runner
    runs-on: [cml-gpu]
    timeout-minutes: 50400 # 35 days
    container:
      image: ghcr.io/iterative/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc pull
          python train.py