name: test
on:
  push:
    branches:
      - finalunittest
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - name: Install dependencies
        run: make requirements
      - name: Get data
        run: dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: $
      - name: Execute tests
        run: pytest tests/tagifai
      - name: Auto linting
        run: black --check --verbose .